### ISSUE TITLE
Update about blksnap

### ISSUE THREAD

**Issue by Fantu** [cloudbase/coriolis-snapshot-agent#14]
Hi, I saw from readme that this project (I randomly saw this now during a google search) use a older version of blksnap found on mailing list, the project is continued, in case you haven't noticed, the repository is here: https://github.com/veeam/blksnap
Latest version of patch for upstream is: https://lore.kernel.org/lkml/20221209142331.26395-1-sergei.shtepa@veeam.com/

Edit:
looking better the readme, from installation part (there is 2 typo Instalation->installation) seems this project are using old veeamsnap that support only up to kernel < 5.18 and is now deprecated: https://github.com/veeam/veeamsnap#disclaimer
blksnap support >=5.10 to latest and there is a work in progress for integrate upstream

**Comment by gabriel-samfira** [comment]
Hi @Fantu !

This project started out with blksnap last year, then moved to veeamsnap as the progress on the ML seemed to have stalled, and we needed support for older versions of the kernel. Eventually we'll move to blksnap for kernel versions that support it and keep veeamsnap for older kernel versions.

This project is still in early stages. We did an initial release, but it was not a priority yet. We'll be gradually updating this project in the following months.

Thanks for bringing VSS like functionality to Linux! :smile:

**Comment by Fantu** [comment]
thanks for reply
This functionality is developer by Veeam and major of work for upstream seems done by @SergeiShtepa, I only giving a very small contribution for trying to help it to get integrate in upstream kernel faster, be more improved as possible and used by major of linux backup softwares as I think is an important thing (as I saw in my sysadmin work, but not only). There are alternative like use lvm or filesystem cow with snapshot (btrfs and zfs); I used lvm, I use btrfs (not always, in major I still use ext4) and tested zfs in past, but as I saw are not applicable and optimal in all cases but only in some, for many cases an "independent" block device level snapshot can be better for the backup part.
Sorry for my bad english.

**Comment by SergeiShtepa** [comment]
> Thanks for bringing VSS like functionality to Linux

Yes, I'm trying to do everything in my power to do this. However, my strength is sometimes not enough.
Many thanks to @Fantu. His participation in the project allows me to look at the project "from a different angle".
I believe that you @gabriel-samfira could also take a feasible part in the project.
For example, a review of documentation for [upstream](https://patchwork.kernel.org./project/linux-block/list/?series=703315) or a comment on [lwn.net](https://lwn.net/Articles/914031/).

I think that for the patch to be successful, we need to show its relevance.
Of course, it is difficult to even predict the chances of success, but even minor project support can increase this chance.

**Comment by Fantu** [comment]
@Dany9966 @gabriel-samfira this is still present the 2 typo in https://github.com/cloudbase/coriolis-snapshot-agent#instalation

**Comment by Dany9966** [comment]
> @Dany9966 @gabriel-samfira there is still present the 3 typo (instalation) in https://github.com/cloudbase/coriolis-snapshot-agent#instalation

Yes, thanks for the heads-up! We'll be updating the whole documentation either way, to match the latest changes.
